theme:           jekyll-theme-cayman
title:           Stargazing
description:     A beautiful sky animation with colorful and moving stars
is_user_page:    false
is_project_page: true
show_downloads:  true
